### ISSUE TITLE
Login IT-Level 2 not working

### ISSUE THREAD

**Issue by BallisticDK** [AnOlsen/ankr-management#48]
people in it level 1 group are able to toggle and set using SNMP SET

**Comment by AnOlsen** [comment]
User class has a method on it named isLevelTwo, which apparently is not working.

It needs to check the groups attribute on the user, which is a collection, if it contains IT-Level-2 group.

It's used in the DatapointController, with toggleInterface. Auth::user()->isLevelTwo. Auth::user() gets the currently signed in user

**Comment by BallisticDK** [comment]
Added if sentence to set method, for testing.

**Comment by BallisticDK** [comment]
Added auth to doSet and toggle.
